# Generated by Django 4.2.10 on 2026-02-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('receiver')), _negated=True), name='no_self_friend_request'),
        ),
    ]
