# Generated by Django 4.2.10 on 2026-02-18 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('business', 'Business'), ('community', 'Community'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('government', 'Government'), ('nonprofit', 'Non-profit'), ('other', 'Other')], default='other', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pages/avatars/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='pages/covers/')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['-followers_count'],
            },
        ),
        migrations.CreateModel(
            name='PageFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='pages.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'page_follows',
                'unique_together': {('page', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PageAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('analyst', 'Analyst')], default='editor', max_length=10)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='pages.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'page_admins',
                'unique_together': {('page', 'user')},
            },
        ),
    ]
